### ISSUE TITLE
Confirm that we are clear on what is and isn't allowed under an infoset.

### ISSUE THREAD

**Issue by hsorby** [cellml/cellml-specification#115]
When we say a `connection` element MAY have a `map_connections` element as a child are we eliminating the possibility of having a `reset` element as a descendant of a `connection` element.

We believe we have such a statement but we need to confirm it.

**Comment by hsorby** [comment]
Here is the statement from the spec. that covers this I think

```
Specific information items MUST NOT appear in a CellML infoset except where explicitly allowed by this specification, or where allowed by a normative specification referenced by this specification.
```

**Comment by hsorby** [comment]
My question is does this work for the `MAY` statements?

**Comment by kerimoyle** [comment]
I think if the MAY refers to quantity of the specified item then we're ok.  If it refers to the type of item, then we're in trouble.  Since we specify the type each time, I think we're fine ...
![image](https://user-images.githubusercontent.com/46887220/77963816-84b56800-733a-11ea-9116-d7634cbc6ee3.png)
