### ISSUE TITLE
Build normative spec. by default?

### ISSUE THREAD

**Issue by hsorby** [cellml/cellml-specification#167]
Should we build the normative spec. by default and the combined informative and normative spec. as an option?

**Comment by agarny** [comment]
This is indeed what I would expect and would like to see.

**Comment by kerimoyle** [comment]
I reckon so :) at the very least until the informative spec is ready.

**Comment by agarny** [comment]
As far as I am concerned, even after the informative spec is ready.

**Comment by MichaelClerx** [comment]
Normative-only is now the default, but haven't found a way to make "informative+normative HTML" the default. Probably not possible without heavily changing the way sphinx Makefile usually works (see #284)

**Comment by kerimoyle** [comment]
I started experimenting with this by making the PDF build simply exclude all of the containers that held the informative stuff, either using the "only:: html" directive, or by pointing to a different file (ie: the HTML shows the entire thing because it builds fileA.rst; the PDF shows the normative becuase it builds fileB.rst).  That was a while ago, and I think that there is too much magical pixiedust inside the current setup doing other stuff to go back to that now ... ?

**Comment by MichaelClerx** [comment]
Discussion seems to have moved to #296
