### ISSUE TITLE
3.10 language: remove 3.10.4?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#171]
3.10.4: CellML models MUST NOT contain any pair of map_variables elements which duplicates an existing arc in the variable equivalence network.
3.10.5: The variable equivalence network MUST NOT contain any cycles.

If we have point 5, does point 4 become redundant? A - B - A is a cycle?

**Comment by kerimoyle** [comment]
... and when it comes down to it, why are we not allowed cycles in the first place??  Surely it should be more of a matter of having a definition somewhere in the set/network (just one, not more) as for any other variable?  Why do we care how it got there?

**Comment by MichaelClerx** [comment]
Agreed with the idea that 3.10.4 is redundant (since edges don't have a direction)

I like the rule of not allowing cycles though. It makes it easier to work with a (n already validated) CellML model, you can traverse connections without having to check for cycles.

It also means you can't create an infinite number of models equivalent to a given model by just re-adding the same `<map_variables>` elements over and over again.

Finally I just think it's pleasing! The sparsest graph that does what we want it to, has no cycles. Adding cycles just creates redundant extra flappy bits of CellML that I'd rather be without

**Comment by MichaelClerx** [comment]
use different terminology to describe the "variable equivalence network"?
Pros of "network
