### ISSUE TITLE
Units reference wording

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#188]
> 1. A units reference SHALL be a CellML identifier** and SHALL be interpreted dependent on the context of the CellML model in which it occurs, according to the units referencing rules defined later in this section**.

What is that bold bit all about? *Everything* in a cellml model "shall be interpreted dependent on the context of the model in which it occurs", and everything in a model shall be interpreted according to the rules in the spec. Why on earth are we stating that?

**Comment by MichaelClerx** [comment]
Does this really need to be so complicated?

> 1. Where, within the same infoset, a units element has a name attribute identical to the units reference, the units reference SHALL refer to that units element.
> 2. Where there is an import units element in the CellML infoset, such that the import units
element has a name attribute identical to the units reference, then the units reference SHALL be treated with respect to referencing rules as if the units reference appeared in the imported infoset, and referring to the name specified in the units_ref attribute of the import units element.
> 3. Where the units reference is equal to the value in the “Name” column of the Built-in units table, then the units reference SHALL be a reference to the built-in units corresponding to that row of the table.

All we're saying is a units reference must be to (3) a built-in unit, (2) the name of a "units" in the same model, or (3) the name of an "import units" in the same model ?

**Comment by MichaelClerx** [comment]
The current text doesn't seem to say that these 3 options are exhaustive, it just describes 3 scenarios without stating they're the only ones allowed

**Comment by MichaelClerx** [comment]
Also still don't get why we have a "symbol" and a "common definition" column. They are never mentioned in the spec, you don't need them to interpret the spec, they're not part of CellML. We don't have a nice info block with the history of variables either, or some background on MathML.

**Comment by kerimoyle** [comment]
They're both a consequence of the radians debate :). In order to say that radians are dimensionless but really length/length, we added the common definitions column.  In order to make that column actually readable, we added the symbol column ... I think that while it's not strictly necessary it would help people understand the ideas behind unit reduction, especially when the unit reduction is in a form they're not used to seeing.  I don't see the harm?

> Everything in a cellml model "shall be interpreted dependent on the context of the model in which it occurs", and everything in a model shall be interpreted according to the rules in the spec. Why on earth are we stating that?

This is explained (as much as I understand it) in the example.  I think it's saying that internal references within the imported items are honoured, rather than defaulting to the importing context: ie, the model in which it occurs = the model from which it was imported =/= the model which imported it?  Not sure why my example isn't being rendered at the moment though, but you can see it here: https://github.com/cellml/cellml-specification/pull/148/files

**Comment by MichaelClerx** [comment]
Will be addressed in #207, but also trying to do an emergency fix now.
