### ISSUE TITLE
Section numbering

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#24]
I've made a bunch of test files for CellML 1.0 by systematically going through the spec and making tests that meet or brake each rule. It was really helpful for this to name them after the rule numbers in the spec. Next step is to transpile them to 1.1 and correct for any differences + add new tests for the new features.

So, this gave me an idea for 2.0.
Could we come up with some numbering system that would allow 2.1 to retain the same numbers as 2.0? For example, the bits before the elements are introduced could be A1, A2, etc.
Then the bit with the elements could be B1, B2, etc.
Then the bit about interpretation could be C1, C2, something like that?

**Comment by nickerso** [comment]
I like this idea!

**Comment by kerimoyle** [comment]
How do you want to deal with changes to resets?  Would you need to keep a chapter B13 or no?  See #26

**Comment by kerimoyle** [comment]
I'm writing this into the rst version, but I need to know two things:
- What to call Section A? (what used to be chapters 1-3)
- In Section C: Interpretation there is now just the one section (previously chapter 19).  I'd like to remove the redundant heading so that the internal subsections are effectively "promoted" by one level.  This means what used to be 19.1.1 becomes C.1.1 instead of C.1.1.1?  Let me know if that's going to mess anything up ...?

Thoughts ... @agarny @MichaelClerx @hsorby @nickerso

**Comment by agarny** [comment]
Section A: Preamble?
Re section C: there is nothing to mess up at this stage (the spec is not final), so if I were you I would do whatever you think is right.

**Comment by hsorby** [comment]
Seems like a good approach to me.
