### ISSUE TITLE
Add final URL to normative prologue

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#290]
... when we know what it is ...

**Comment by MichaelClerx** [comment]
@nickerso ?

**Comment by hsorby** [comment]
I'll have a crack at this again:
```
https://cellml.org/specification/cellml_2.0/cellml_2_0_normative_specification.pdf
```

**Comment by agarny** [comment]
I guess I must have missed it, but do we really want to use a `.` for the `cellml_2.0` bit and an `_` for the PDF filename? I know that I was in favour of the underscore for the PDF filename, but seeing it in context, it looks a bit odd since we want/need to use `.` for the `cellml_2.0` bit (to be consistent with previous versions of CellML). Argh, I am in two minds about this now.

Warning, warning, CellML Specification overload!

**Comment by kerimoyle** [comment]
I think it's better to avoid using `.` in URLs in general, so would rather have:
```
https://cellml.org/specification/cellml_2_0/cellml_2_0_normative_specification.pdf
```
It's a bit ugly though :|

**Comment by agarny** [comment]
The problem is that we already have https://cellml.org/specifications/cellml_1.0 and https://cellml.org/specification/cellml_1.1, so to have https://cellml.org/specification/cellml_2_0 would look really odd.

Actually, we have https://www.cellml.org/specifications/cellml_1.0 and https://www.cellml.org/specifications/cellml_1.1 (note the "www"!), which work fine but not https://cellml.org/specifications/cellml_1.0 and https://cellml.org/specification/cellml_1.1. IOW, there is no redirect to the `www`... Something for @nickerso or @metatoaster?

**Comment by agarny** [comment]
Oops, it's actually https://cellml.org/specifications/cellml_1.0 and https://cellml.org/specifications/cellml_1.1, and it should be https://cellml.org/specifications/cellml_2.0. IOW, "specifications", not "specification"!
