### ISSUE TITLE
Reset order could be a real?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#38]
Then, if you have order 1 and order 2, it's still possible to insert something in between

**Comment by hsorby** [comment]
No, I have already tried this one.  It is done so you cannot insert a reset in between to consecutive ordered resets.

**Comment by MichaelClerx** [comment]
And why aren't we allowing that?

**Comment by hsorby** [comment]
The idea is that you can insist that one reset occurs after another, with real orders you can always place a reset in between.

**Comment by hsorby** [comment]
Best practice would say that you allow plenty of space between resets if you are ok with resets occurring inbetween.

**Comment by agarny** [comment]
> The idea is that you can insist that one reset occurs after another, with real orders you can always place a reset in between.

I can't see what would be wrong with allowing that though...?

**Comment by kerimoyle** [comment]
I don't think that allowing it reduces the control that the original creator of the resets has - ie: only allowing integers might give the impression that two must be consecutive, but it's easy to change anyway, so there's no real difference ... ?

**Comment by nickerso** [comment]
Last time we discussed this, we decided that a modeller should be able to specify that certain things happen in a specific order (as their model may depend on certain behaviour) and not have someone reusing the model be able to change that. If a modeller needed to change the orders to insert a new reset into the set then they'd need to edit the source models rather than reuse them (or use SED-ML to edit-on-the-fly...)

**Comment by MichaelClerx** [comment]
Thanks @nickerso !
