### ISSUE TITLE
Import <component>, but encapsulate <component_ref>

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/cellml-specification#44]
<import>
      <component component_ref="my_component" ...
    </import>
    <encapsulation>
      <component_ref component="my_component" />
      ...

So in one place `<component>` is the element and `component_ref` the attribute, and then further down in the document we flip these around?

**Comment by nickerso** [comment]
It does look funny when you write them side by side like that :)

The `import` is actually defining a `component` in the model, so that is right. And the `@component_ref` is the link to the component in the source model. For `encapsulation` the `component_ref` is a reference to a component in the current model with the name given in the `@component`. These have always been confusing :) but are actually clearly described in the spec unambiguously.
