### ISSUE TITLE
Unit equivalence in resets?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/cellml-specification#49]
Since we use the `reset_value` and `test_value` blocks to assign/test values of variables, do we need a statement somewhere that says that their units need to match?  ie: between `reset_value` and `variable`, and `test_value` and `test_variable` ?

See: https://cellml-specification-dev.readthedocs.io/en/latest/reference/specC11_interpretation_of_variable_resets.html

**Comment by agarny** [comment]
In principle, I would say so, but if you think of a "normal" equation, we can have something like `X = Y + Z`, and yet have `X` in *mV*, `Y` in *V* and `Z` in `nV`. So, when it comes to the specifications, I would say that we allow "anything". Then, when it comes to the analysis of the model, we could generate some warnings.

**Comment by kerimoyle** [comment]
But do we really allow "anything"?  Even stuff where the base is not compatible?  eg: `X` in _V_, `Y` in _s_ and `Z` in _m_?

**Comment by agarny** [comment]
As far as I remember, yes, we do. @nickerso to correct me if I am remembering wrong (which is quite possible! :)).

**Comment by MichaelClerx** [comment]
See related issue here https://github.com/cellml/cellml-specification/issues/46

**Comment by nickerso** [comment]
Yep - CellML itself does not care about units within math - that is the domain of the model/modeller. We do care about units in connections because that is the role of modularity in CellML.

This is another area where a model debugging tool could pick up things that are likely bad modelling, but not something that the CellML specification needs to worry about in my view.

**Comment by kerimoyle** [comment]
Great, thanks all.  I'll close this now as it doesn't need addressing in the spec.
